version: "3.9"

services:
  mongo:
    image: mongo
    container_name: mean-ng-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mean-ng-mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mean-ng-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123456

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: mean-ng-client
    stdin_open: true
    ports:
      - 8080:80
    # networks:
    #   - distribution-system-network
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mean-ng-server
    stdin_open: true
    ports:
      - 3001:3000
    environment:
      - DB_MONGO_URL=mongodb://root:example@mongo:27017
    # networks:
    #   - distribution-system-network
    restart: always

  proxy:
    image: nginx:1.17.10
    container_name: mean-ng-proxy
    depends_on:
      - mongo
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

volumes:
  mean-ng-mongo-data:
    driver: local
